language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:jcfp -y
  - sudo apt-get update -q
  - sudo apt-get install sabnzbdplus -y
install:
  - pip install --upgrade -r tests/requirements.txt
script:
  - pytest
notifications:
  email:
    on_success: never
    on_failure: always