environment:
  SAB_NEWSSERVER_HOST:
    secure: 6SvOPWr5ypJeoumXJAZh90DLpk4C/5UAvzwyX7OOUr4=
  SAB_NEWSSERVER_USER:
    secure: Ty3ZG8T5vnacqIFPj5j5hg==
  SAB_NEWSSERVER_PASSWORD:
    secure: bO3XHtWTleVF9AqRV/V/nA==

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r tests/requirements.txt
  - pip install pypiwin32

build_script:
  - python -m pytest